# Generated by Django 5.0.1 on 2024-01-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_created_at_alter_blog_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
